<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Customer;
use App\Models\Department;
use App\Models\City;
use App\Models\Product;
use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Customer::factory(10)->create();
        Vehicle::factory(10)->create();
        Product::factory(100)->create();

        User::factory()->create([
            'type' => 'cc',
            'cc' => '123456789',
            'name' => 'Admin',
            'job' => 'a',
            'email' => 'megadatakit@gmail.com',
            'phone' => '123456789',
            'question' => 'pq',
            'answer' => 'pq zi',
            'password' => Hash::make('123456789'),
            'status' => '1',
        ]);
        User::factory(10)->create();

        Department::factory()->create(['id' => '05', 'name' => 'ANTIOQUIA']);
        Department::factory()->create(['id' => '08', 'name' => 'ATLÁNTICO']);
        Department::factory()->create(['id' => '11', 'name' => 'BOGOTÁ']);
        Department::factory()->create(['id' => '13', 'name' => 'BOLÍVAR']);
        Department::factory()->create(['id' => '15', 'name' => 'BOYACÁ']);
        Department::factory()->create(['id' => '17', 'name' => 'CALDAS']);
        Department::factory()->create(['id' => '18', 'name' => 'CAQUETÁ']);
        Department::factory()->create(['id' => '19', 'name' => 'CAUCA']);
        Department::factory()->create(['id' => '20', 'name' => 'CESAR']);
        Department::factory()->create(['id' => '23', 'name' => 'CÓRDOBA']);
        Department::factory()->create(['id' => '25', 'name' => 'CUNDINAMARCA']);
        Department::factory()->create(['id' => '27', 'name' => 'CHOCÓ']);
        Department::factory()->create(['id' => '41', 'name' => 'HUILA']);
        Department::factory()->create(['id' => '44', 'name' => 'LA GUAJIRA']);
        Department::factory()->create(['id' => '47', 'name' => 'MAGDALENA']);
        Department::factory()->create(['id' => '50', 'name' => 'META']);
        Department::factory()->create(['id' => '52', 'name' => 'NARIÑO']);
        Department::factory()->create(['id' => '54', 'name' => 'NORTE DE SANTANDER']);
        Department::factory()->create(['id' => '63', 'name' => 'QUINDIO']);
        Department::factory()->create(['id' => '66', 'name' => 'RISARALDA']);
        Department::factory()->create(['id' => '68', 'name' => 'SANTANDER']);
        Department::factory()->create(['id' => '70', 'name' => 'SUCRE']);
        Department::factory()->create(['id' => '73', 'name' => 'TOLIMA']);
        Department::factory()->create(['id' => '76', 'name' => 'VALLE DEL CAUCA']);
        Department::factory()->create(['id' => '81', 'name' => 'ARAUCA']);
        Department::factory()->create(['id' => '85', 'name' => 'CASANARE']);
        Department::factory()->create(['id' => '86', 'name' => 'PUTUMAYO']);
        Department::factory()->create(['id' => '88', 'name' => 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA']);
        Department::factory()->create(['id' => '91', 'name' => 'AMAZONAS']);
        Department::factory()->create(['id' => '94', 'name' => 'GUAINÁ']);
        Department::factory()->create(['id' => '95', 'name' => 'GUAVIARE']);
        Department::factory()->create(['id' => '97', 'name' => 'VAUPÉS']);
        Department::factory()->create(['id' => '99', 'name' => 'VICHADA']);


        City::factory()->create(['name' => 'Medellín', 'department_id' => '05']);
        City::factory()->create(['name' => 'Abejorral', 'department_id' => '05']);
        City::factory()->create(['name' => 'Abriaquí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Alejandría', 'department_id' => '05']);
        City::factory()->create(['name' => 'Amagá', 'department_id' => '05']);
        City::factory()->create(['name' => 'Amalfi', 'department_id' => '05']);
        City::factory()->create(['name' => 'Andes', 'department_id' => '05']);
        City::factory()->create(['name' => 'Angelópolis', 'department_id' => '05']);
        City::factory()->create(['name' => 'Angostura', 'department_id' => '05']);
        City::factory()->create(['name' => 'Anorí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Santafé de Antioquia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Anza', 'department_id' => '05']);
        City::factory()->create(['name' => 'Apartadó', 'department_id' => '05']);
        City::factory()->create(['name' => 'Arboletes', 'department_id' => '05']);
        City::factory()->create(['name' => 'Argelia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Armenia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Barbosa', 'department_id' => '05']);
        City::factory()->create(['name' => 'Belmira', 'department_id' => '05']);
        City::factory()->create(['name' => 'Bello', 'department_id' => '05']);
        City::factory()->create(['name' => 'Betania', 'department_id' => '05']);
        City::factory()->create(['name' => 'Betulia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Ciudad Bolívar', 'department_id' => '05']);
        City::factory()->create(['name' => 'Briceño', 'department_id' => '05']);
        City::factory()->create(['name' => 'Buriticá', 'department_id' => '05']);
        City::factory()->create(['name' => 'Cáceres', 'department_id' => '05']);
        City::factory()->create(['name' => 'Caicedo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Caldas', 'department_id' => '05']);
        City::factory()->create(['name' => 'Campamento', 'department_id' => '05']);
        City::factory()->create(['name' => 'Cañasgordas', 'department_id' => '05']);
        City::factory()->create(['name' => 'Caracolí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Caramanta', 'department_id' => '05']);
        City::factory()->create(['name' => 'Carepa', 'department_id' => '05']);
        City::factory()->create(['name' => 'El Carmen de Viboral', 'department_id' => '05']);
        City::factory()->create(['name' => 'Carolina', 'department_id' => '05']);
        City::factory()->create(['name' => 'Caucasia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Chigorodó', 'department_id' => '05']);
        City::factory()->create(['name' => 'Cisneros', 'department_id' => '05']);
        City::factory()->create(['name' => 'Cocorná', 'department_id' => '05']);
        City::factory()->create(['name' => 'Concepción', 'department_id' => '05']);
        City::factory()->create(['name' => 'Concordia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Copacabana', 'department_id' => '05']);
        City::factory()->create(['name' => 'Dabeiba', 'department_id' => '05']);
        City::factory()->create(['name' => 'Don Matías', 'department_id' => '05']);
        City::factory()->create(['name' => 'Ebéjico', 'department_id' => '05']);
        City::factory()->create(['name' => 'El Bagre', 'department_id' => '05']);
        City::factory()->create(['name' => 'Entrerrios', 'department_id' => '05']);
        City::factory()->create(['name' => 'Envigado', 'department_id' => '05']);
        City::factory()->create(['name' => 'Fredonia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Frontino', 'department_id' => '05']);
        City::factory()->create(['name' => 'Giraldo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Girardota', 'department_id' => '05']);
        City::factory()->create(['name' => 'Gómez Plata', 'department_id' => '05']);
        City::factory()->create(['name' => 'Granada', 'department_id' => '05']);
        City::factory()->create(['name' => 'Guadalupe', 'department_id' => '05']);
        City::factory()->create(['name' => 'Guarne', 'department_id' => '05']);
        City::factory()->create(['name' => 'Guatapé', 'department_id' => '05']);
        City::factory()->create(['name' => 'Heliconia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Hispania', 'department_id' => '05']);
        City::factory()->create(['name' => 'Itagui', 'department_id' => '05']);
        City::factory()->create(['name' => 'Ituango', 'department_id' => '05']);
        City::factory()->create(['name' => 'Jardín', 'department_id' => '05']);
        City::factory()->create(['name' => 'Jericó', 'department_id' => '05']);
        City::factory()->create(['name' => 'La Ceja', 'department_id' => '05']);
        City::factory()->create(['name' => 'La Estrella', 'department_id' => '05']);
        City::factory()->create(['name' => 'La Pintada', 'department_id' => '05']);
        City::factory()->create(['name' => 'La Unión', 'department_id' => '05']);
        City::factory()->create(['name' => 'Liborina', 'department_id' => '05']);
        City::factory()->create(['name' => 'Maceo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Marinilla', 'department_id' => '05']);
        City::factory()->create(['name' => 'Montebello', 'department_id' => '05']);
        City::factory()->create(['name' => 'Murindó', 'department_id' => '05']);
        City::factory()->create(['name' => 'Mutatá', 'department_id' => '05']);
        City::factory()->create(['name' => 'Nariño', 'department_id' => '05']);
        City::factory()->create(['name' => 'Necoclí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Nechí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Olaya', 'department_id' => '05']);
        City::factory()->create(['name' => 'Peñol', 'department_id' => '05']);
        City::factory()->create(['name' => 'Peque', 'department_id' => '05']);
        City::factory()->create(['name' => 'Pueblorrico', 'department_id' => '05']);
        City::factory()->create(['name' => 'Puerto Berrío', 'department_id' => '05']);
        City::factory()->create(['name' => 'Puerto Nare', 'department_id' => '05']);
        City::factory()->create(['name' => 'Puerto Triunfo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Remedios', 'department_id' => '05']);
        City::factory()->create(['name' => 'Retiro', 'department_id' => '05']);
        City::factory()->create(['name' => 'Rionegro', 'department_id' => '05']);
        City::factory()->create(['name' => 'Sabanalarga', 'department_id' => '05']);
        City::factory()->create(['name' => 'Sabaneta', 'department_id' => '05']);
        City::factory()->create(['name' => 'Salgar', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Andrés de Cuerquía', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Carlos', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Francisco', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Jerónimo', 'department_id' => '05']);
        City::factory()->create(['name' => 'San José de La Montaña', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Juan de Urabá', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Luis', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Pedro', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Pedro de Uraba', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Rafael', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Roque', 'department_id' => '05']);
        City::factory()->create(['name' => 'San Vicente', 'department_id' => '05']);
        City::factory()->create(['name' => 'Santa Bárbara', 'department_id' => '05']);
        City::factory()->create(['name' => 'Santa Rosa de Osos', 'department_id' => '05']);
        City::factory()->create(['name' => 'Santo Domingo', 'department_id' => '05']);
        City::factory()->create(['name' => 'El Santuario', 'department_id' => '05']);
        City::factory()->create(['name' => 'Segovia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Sonsón', 'department_id' => '05']);
        City::factory()->create(['name' => 'Sopetrán', 'department_id' => '05']);
        City::factory()->create(['name' => 'Támesis', 'department_id' => '05']);
        City::factory()->create(['name' => 'Tarazá', 'department_id' => '05']);
        City::factory()->create(['name' => 'Tarso', 'department_id' => '05']);
        City::factory()->create(['name' => 'Titiribí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Toledo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Turbo', 'department_id' => '05']);
        City::factory()->create(['name' => 'Uramita', 'department_id' => '05']);
        City::factory()->create(['name' => 'Urrao', 'department_id' => '05']);
        City::factory()->create(['name' => 'Valdivia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Valparaíso', 'department_id' => '05']);
        City::factory()->create(['name' => 'Vegachí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Venecia', 'department_id' => '05']);
        City::factory()->create(['name' => 'Vigía del Fuerte', 'department_id' => '05']);
        City::factory()->create(['name' => 'Yalí', 'department_id' => '05']);
        City::factory()->create(['name' => 'Yarumal', 'department_id' => '05']);
        City::factory()->create(['name' => 'Yolombó', 'department_id' => '05']);
        City::factory()->create(['name' => 'Yondó', 'department_id' => '05']);
        City::factory()->create(['name' => 'Zaragoza', 'department_id' => '05']);
        City::factory()->create(['name' => 'Barranquilla', 'department_id' => '08']);
        City::factory()->create(['name' => 'Baranoa', 'department_id' => '08']);
        City::factory()->create(['name' => 'Campo de La Cruz', 'department_id' => '08']);
        City::factory()->create(['name' => 'Candelaria', 'department_id' => '08']);
        City::factory()->create(['name' => 'Galapa', 'department_id' => '08']);
        City::factory()->create(['name' => 'Juan de Acosta', 'department_id' => '08']);
        City::factory()->create(['name' => 'Luruaco', 'department_id' => '08']);
        City::factory()->create(['name' => 'Malambo', 'department_id' => '08']);
        City::factory()->create(['name' => 'Manatí', 'department_id' => '08']);
        City::factory()->create(['name' => 'Palmar de Varela', 'department_id' => '08']);
        City::factory()->create(['name' => 'Piojó', 'department_id' => '08']);
        City::factory()->create(['name' => 'Polonuevo', 'department_id' => '08']);
        City::factory()->create(['name' => 'Ponedera', 'department_id' => '08']);
        City::factory()->create(['name' => 'Puerto Colombia', 'department_id' => '08']);
        City::factory()->create(['name' => 'Repelón', 'department_id' => '08']);
        City::factory()->create(['name' => 'Sabanagrande', 'department_id' => '08']);
        City::factory()->create(['name' => 'Sabanalarga', 'department_id' => '08']);
        City::factory()->create(['name' => 'Santa Lucía', 'department_id' => '08']);
        City::factory()->create(['name' => 'Santo Tomás', 'department_id' => '08']);
        City::factory()->create(['name' => 'Soledad', 'department_id' => '08']);
        City::factory()->create(['name' => 'Suan', 'department_id' => '08']);
        City::factory()->create(['name' => 'Tubará', 'department_id' => '08']);
        City::factory()->create(['name' => 'Usiacurí', 'department_id' => '08']);
        City::factory()->create(['name' => 'Bogotá D.C', 'department_id' => '11']);
        City::factory()->create(['name' => 'Cartagena', 'department_id' => '13']);
        City::factory()->create(['name' => 'Achí', 'department_id' => '13']);
        City::factory()->create(['name' => 'Altos del Rosario', 'department_id' => '13']);
        City::factory()->create(['name' => 'Arenal', 'department_id' => '13']);
        City::factory()->create(['name' => 'Arjona', 'department_id' => '13']);
        City::factory()->create(['name' => 'Arroyohondo', 'department_id' => '13']);
        City::factory()->create(['name' => 'Barranco de Loba', 'department_id' => '13']);
        City::factory()->create(['name' => 'Calamar', 'department_id' => '13']);
        City::factory()->create(['name' => 'Cantagallo', 'department_id' => '13']);
        City::factory()->create(['name' => 'Cicuco', 'department_id' => '13']);
        City::factory()->create(['name' => 'Córdoba', 'department_id' => '13']);
        City::factory()->create(['name' => 'Clemencia', 'department_id' => '13']);
        City::factory()->create(['name' => 'El Carmen de Bolívar', 'department_id' => '13']);
        City::factory()->create(['name' => 'El Guamo', 'department_id' => '13']);
        City::factory()->create(['name' => 'El Peñón', 'department_id' => '13']);
        City::factory()->create(['name' => 'Hatillo de Loba', 'department_id' => '13']);
        City::factory()->create(['name' => 'Magangué', 'department_id' => '13']);
        City::factory()->create(['name' => 'Mahates', 'department_id' => '13']);
        City::factory()->create(['name' => 'Margarita', 'department_id' => '13']);
        City::factory()->create(['name' => 'María la Baja', 'department_id' => '13']);
        City::factory()->create(['name' => 'Montecristo', 'department_id' => '13']);
        City::factory()->create(['name' => 'Mompós', 'department_id' => '13']);
        City::factory()->create(['name' => 'Morales', 'department_id' => '13']);
        City::factory()->create(['name' => 'Norosí', 'department_id' => '13']);
        City::factory()->create(['name' => 'Pinillos', 'department_id' => '13']);
        City::factory()->create(['name' => 'Regidor', 'department_id' => '13']);
        City::factory()->create(['name' => 'Río Viejo', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Cristóbal', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Estanislao', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Fernando', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Jacinto', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Jacinto del Cauca', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Juan Nepomuceno', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Martín de Loba', 'department_id' => '13']);
        City::factory()->create(['name' => 'San Pablo de Borbur', 'department_id' => '13']);
        City::factory()->create(['name' => 'Santa Catalina', 'department_id' => '13']);
        City::factory()->create(['name' => 'Santa Rosa', 'department_id' => '13']);
        City::factory()->create(['name' => 'Santa Rosa del Sur', 'department_id' => '13']);
        City::factory()->create(['name' => 'Simití', 'department_id' => '13']);
        City::factory()->create(['name' => 'Soplaviento', 'department_id' => '13']);
        City::factory()->create(['name' => 'Talaigua Nuevo', 'department_id' => '13']);
        City::factory()->create(['name' => 'Tiquisio', 'department_id' => '13']);
        City::factory()->create(['name' => 'Turbaco', 'department_id' => '13']);
        City::factory()->create(['name' => 'Turbaná', 'department_id' => '13']);
        City::factory()->create(['name' => 'Villanueva', 'department_id' => '13']);
        City::factory()->create(['name' => 'Zambrano', 'department_id' => '13']);
        City::factory()->create(['name' => 'Tunja', 'department_id' => '15']);
        City::factory()->create(['name' => 'Almeida', 'department_id' => '15']);
        City::factory()->create(['name' => 'Aquitania', 'department_id' => '15']);
        City::factory()->create(['name' => 'Arcabuco', 'department_id' => '15']);
        City::factory()->create(['name' => 'Belén', 'department_id' => '15']);
        City::factory()->create(['name' => 'Berbeo', 'department_id' => '15']);
        City::factory()->create(['name' => 'Betéitiva', 'department_id' => '15']);
        City::factory()->create(['name' => 'Boavita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Boyacá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Briceño', 'department_id' => '15']);
        City::factory()->create(['name' => 'Buena Vista', 'department_id' => '15']);
        City::factory()->create(['name' => 'Busbanzá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Caldas', 'department_id' => '15']);
        City::factory()->create(['name' => 'Campohermoso', 'department_id' => '15']);
        City::factory()->create(['name' => 'Cerinza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chinavita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chiquinquirá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chiscas', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chitaraque', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chivatá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Ciénega', 'department_id' => '15']);
        City::factory()->create(['name' => 'Cómbita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Coper', 'department_id' => '15']);
        City::factory()->create(['name' => 'Corrales', 'department_id' => '15']);
        City::factory()->create(['name' => 'Covarachía', 'department_id' => '15']);
        City::factory()->create(['name' => 'Cubará', 'department_id' => '15']);
        City::factory()->create(['name' => 'Cucaita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Cuítiva', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chíquiza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Chivor', 'department_id' => '15']);
        City::factory()->create(['name' => 'Duitama', 'department_id' => '15']);
        City::factory()->create(['name' => 'El Cocuy', 'department_id' => '15']);
        City::factory()->create(['name' => 'El Espino', 'department_id' => '15']);
        City::factory()->create(['name' => 'Firavitoba', 'department_id' => '15']);
        City::factory()->create(['name' => 'Floresta', 'department_id' => '15']);
        City::factory()->create(['name' => 'Gachantivá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Gameza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Garagoa', 'department_id' => '15']);
        City::factory()->create(['name' => 'Guacamayas', 'department_id' => '15']);
        City::factory()->create(['name' => 'Guateque', 'department_id' => '15']);
        City::factory()->create(['name' => 'Guayatá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Güicán', 'department_id' => '15']);
        City::factory()->create(['name' => 'Iza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Jenesano', 'department_id' => '15']);
        City::factory()->create(['name' => 'Jericó', 'department_id' => '15']);
        City::factory()->create(['name' => 'Labranzagrande', 'department_id' => '15']);
        City::factory()->create(['name' => 'La Capilla', 'department_id' => '15']);
        City::factory()->create(['name' => 'La Victoria', 'department_id' => '15']);
        City::factory()->create(['name' => 'La Uvita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Villa De Leyva', 'department_id' => '15']);
        City::factory()->create(['name' => 'Macanal', 'department_id' => '15']);
        City::factory()->create(['name' => 'Maripí', 'department_id' => '15']);
        City::factory()->create(['name' => 'Miraflores', 'department_id' => '15']);
        City::factory()->create(['name' => 'Mongua', 'department_id' => '15']);
        City::factory()->create(['name' => 'Monguí', 'department_id' => '15']);
        City::factory()->create(['name' => 'Moniquirá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Motavita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Muzo', 'department_id' => '15']);
        City::factory()->create(['name' => 'Nobsa', 'department_id' => '15']);
        City::factory()->create(['name' => 'Nuevo Colón', 'department_id' => '15']);
        City::factory()->create(['name' => 'Oicatá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Otanche', 'department_id' => '15']);
        City::factory()->create(['name' => 'Pachavita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Páez', 'department_id' => '15']);
        City::factory()->create(['name' => 'Paipa', 'department_id' => '15']);
        City::factory()->create(['name' => 'Pajarito', 'department_id' => '15']);
        City::factory()->create(['name' => 'Panqueba', 'department_id' => '15']);
        City::factory()->create(['name' => 'Pauna', 'department_id' => '15']);
        City::factory()->create(['name' => 'Paya', 'department_id' => '15']);
        City::factory()->create(['name' => 'Paz De Río', 'department_id' => '15']);
        City::factory()->create(['name' => 'Pesca', 'department_id' => '15']);
        City::factory()->create(['name' => 'Pisba', 'department_id' => '15']);
        City::factory()->create(['name' => 'Puerto Boyacá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Quípama', 'department_id' => '15']);
        City::factory()->create(['name' => 'Ramiriquí', 'department_id' => '15']);
        City::factory()->create(['name' => 'Ráquira', 'department_id' => '15']);
        City::factory()->create(['name' => 'Rondón', 'department_id' => '15']);
        City::factory()->create(['name' => 'Saboyá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sáchica', 'department_id' => '15']);
        City::factory()->create(['name' => 'Samacá', 'department_id' => '15']);
        City::factory()->create(['name' => 'San Eduardo', 'department_id' => '15']);
        City::factory()->create(['name' => 'San José De Pare', 'department_id' => '15']);
        City::factory()->create(['name' => 'San Luis De Gaceno', 'department_id' => '15']);
        City::factory()->create(['name' => 'San Mateo', 'department_id' => '15']);
        City::factory()->create(['name' => 'San Miguel De Sema', 'department_id' => '15']);
        City::factory()->create(['name' => 'San Pablo De Borbur', 'department_id' => '15']);
        City::factory()->create(['name' => 'Santana', 'department_id' => '15']);
        City::factory()->create(['name' => 'Santa María', 'department_id' => '15']);
        City::factory()->create(['name' => 'Santa Rosa De Viterbo', 'department_id' => '15']);
        City::factory()->create(['name' => 'Santa Sofía', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sativanorte', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sativasur', 'department_id' => '15']);
        City::factory()->create(['name' => 'Siachoque', 'department_id' => '15']);
        City::factory()->create(['name' => 'Soatá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Socotá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Socha', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sogamoso', 'department_id' => '15']);
        City::factory()->create(['name' => 'Somondoco', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sora', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sotaquirá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Soracá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Susacón', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sutamarchán', 'department_id' => '15']);
        City::factory()->create(['name' => 'Sutatenza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tasco', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tenza', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tibaná', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tibasosa', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tinjacá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tipacoque', 'department_id' => '15']);
        City::factory()->create(['name' => 'Toca', 'department_id' => '15']);
        City::factory()->create(['name' => 'Togüí', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tópaga', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tota', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tununguá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Turmequé', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tuta', 'department_id' => '15']);
        City::factory()->create(['name' => 'Tutazá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Umbita', 'department_id' => '15']);
        City::factory()->create(['name' => 'Ventaquemada', 'department_id' => '15']);
        City::factory()->create(['name' => 'Viracachá', 'department_id' => '15']);
        City::factory()->create(['name' => 'Zetaquira', 'department_id' => '15']);
        City::factory()->create(['name' => 'Manizales', 'department_id' => '17']);
        City::factory()->create(['name' => 'Aguadas', 'department_id' => '17']);
        City::factory()->create(['name' => 'Anserma', 'department_id' => '17']);
        City::factory()->create(['name' => 'Aranzazu', 'department_id' => '17']);
        City::factory()->create(['name' => 'Belalcázar', 'department_id' => '17']);
        City::factory()->create(['name' => 'Chinchiná', 'department_id' => '17']);
        City::factory()->create(['name' => 'Filadelfia', 'department_id' => '17']);
        City::factory()->create(['name' => 'La Dorada', 'department_id' => '17']);
        City::factory()->create(['name' => 'La Merced', 'department_id' => '17']);
        City::factory()->create(['name' => 'Manzanares', 'department_id' => '17']);
        City::factory()->create(['name' => 'Marmato', 'department_id' => '17']);
        City::factory()->create(['name' => 'Marquetalia', 'department_id' => '17']);
        City::factory()->create(['name' => 'Marulanda', 'department_id' => '17']);
        City::factory()->create(['name' => 'Neira', 'department_id' => '17']);
        City::factory()->create(['name' => 'Norcasia', 'department_id' => '17']);
        City::factory()->create(['name' => 'Pácora', 'department_id' => '17']);
        City::factory()->create(['name' => 'Palestina', 'department_id' => '17']);
        City::factory()->create(['name' => 'Pensilvania', 'department_id' => '17']);
        City::factory()->create(['name' => 'Riosucio', 'department_id' => '17']);
        City::factory()->create(['name' => 'Risaralda', 'department_id' => '17']);
        City::factory()->create(['name' => 'Salamina', 'department_id' => '17']);
        City::factory()->create(['name' => 'Samaná', 'department_id' => '17']);
        City::factory()->create(['name' => 'San José', 'department_id' => '17']);
        City::factory()->create(['name' => 'Supía', 'department_id' => '17']);
        City::factory()->create(['name' => 'Victoria', 'department_id' => '17']);
        City::factory()->create(['name' => 'Villamaría', 'department_id' => '17']);
        City::factory()->create(['name' => 'Viterbo', 'department_id' => '17']);
        City::factory()->create(['name' => 'Florencia', 'department_id' => '18']);
        City::factory()->create(['name' => 'Albania', 'department_id' => '18']);
        City::factory()->create(['name' => 'Belén de Los Andaquies', 'department_id' => '18']);
        City::factory()->create(['name' => 'Cartagena del Chairá', 'department_id' => '18']);
        City::factory()->create(['name' => 'Curillo', 'department_id' => '18']);
        City::factory()->create(['name' => 'El Doncello', 'department_id' => '18']);
        City::factory()->create(['name' => 'El Paujil', 'department_id' => '18']);
        City::factory()->create(['name' => 'La Montañita', 'department_id' => '18']);
        City::factory()->create(['name' => 'Milán', 'department_id' => '18']);
        City::factory()->create(['name' => 'Morelia', 'department_id' => '18']);
        City::factory()->create(['name' => 'Puerto Rico', 'department_id' => '18']);
        City::factory()->create(['name' => 'San José del Fragua', 'department_id' => '18']);
        City::factory()->create(['name' => 'San Vicente del Caguán', 'department_id' => '18']);
        City::factory()->create(['name' => 'Solano', 'department_id' => '18']);
        City::factory()->create(['name' => 'Solita', 'department_id' => '18']);
        City::factory()->create(['name' => 'Valparaíso', 'department_id' => '18']);
        City::factory()->create(['name' => 'Popayán', 'department_id' => '19']);
        City::factory()->create(['name' => 'Almaguer', 'department_id' => '19']);
        City::factory()->create(['name' => 'Argelia', 'department_id' => '19']);
        City::factory()->create(['name' => 'Balboa', 'department_id' => '19']);
        City::factory()->create(['name' => 'Bolívar', 'department_id' => '19']);
        City::factory()->create(['name' => 'Buenos Aires', 'department_id' => '19']);
        City::factory()->create(['name' => 'Cajibío', 'department_id' => '19']);
        City::factory()->create(['name' => 'Caldono', 'department_id' => '19']);
        City::factory()->create(['name' => 'Caloto', 'department_id' => '19']);
        City::factory()->create(['name' => 'Corinto', 'department_id' => '19']);
        City::factory()->create(['name' => 'El Tambo', 'department_id' => '19']);
        City::factory()->create(['name' => 'Florencia', 'department_id' => '19']);
        City::factory()->create(['name' => 'Guachené', 'department_id' => '19']);
        City::factory()->create(['name' => 'Guapi', 'department_id' => '19']);
        City::factory()->create(['name' => 'Inzá', 'department_id' => '19']);
        City::factory()->create(['name' => 'Jambaló', 'department_id' => '19']);
        City::factory()->create(['name' => 'La Sierra', 'department_id' => '19']);
        City::factory()->create(['name' => 'La Vega', 'department_id' => '19']);
        City::factory()->create(['name' => 'López de Micay', 'department_id' => '19']);
        City::factory()->create(['name' => 'Mercaderes', 'department_id' => '19']);
        City::factory()->create(['name' => 'Miranda', 'department_id' => '19']);
        City::factory()->create(['name' => 'Morales', 'department_id' => '19']);
        City::factory()->create(['name' => 'Padilla', 'department_id' => '19']);
        City::factory()->create(['name' => 'Páez', 'department_id' => '19']);
        City::factory()->create(['name' => 'Patía', 'department_id' => '19']);
        City::factory()->create(['name' => 'Piamonte', 'department_id' => '19']);
        City::factory()->create(['name' => 'Piendamó', 'department_id' => '19']);
        City::factory()->create(['name' => 'Puerto Tejada', 'department_id' => '19']);
        City::factory()->create(['name' => 'Puracé', 'department_id' => '19']);
        City::factory()->create(['name' => 'Rosas', 'department_id' => '19']);
        City::factory()->create(['name' => 'San Sebastián', 'department_id' => '19']);
        City::factory()->create(['name' => 'Santander de Quilichao', 'department_id' => '19']);
        City::factory()->create(['name' => 'Santa Rosa', 'department_id' => '19']);
        City::factory()->create(['name' => 'Silvia', 'department_id' => '19']);
        City::factory()->create(['name' => 'Sotara', 'department_id' => '19']);
        City::factory()->create(['name' => 'Suárez', 'department_id' => '19']);
        City::factory()->create(['name' => 'Sucre', 'department_id' => '19']);
        City::factory()->create(['name' => 'Timbío', 'department_id' => '19']);
        City::factory()->create(['name' => 'Timbiquí', 'department_id' => '19']);
        City::factory()->create(['name' => 'Toribio', 'department_id' => '19']);
        City::factory()->create(['name' => 'Totoró', 'department_id' => '19']);
        City::factory()->create(['name' => 'Villa Rica', 'department_id' => '19']);
        City::factory()->create(['name' => 'Valledupar', 'department_id' => '20']);
        City::factory()->create(['name' => 'Aguachica', 'department_id' => '20']);
        City::factory()->create(['name' => 'Agustín Codazzi', 'department_id' => '20']);
        City::factory()->create(['name' => 'Astrea', 'department_id' => '20']);
        City::factory()->create(['name' => 'Becerril', 'department_id' => '20']);
        City::factory()->create(['name' => 'Bosconia', 'department_id' => '20']);
        City::factory()->create(['name' => 'Chimichagua', 'department_id' => '20']);
        City::factory()->create(['name' => 'Chiriguaná', 'department_id' => '20']);
        City::factory()->create(['name' => 'Curumaní', 'department_id' => '20']);
        City::factory()->create(['name' => 'El Copey', 'department_id' => '20']);
        City::factory()->create(['name' => 'El Paso', 'department_id' => '20']);
        City::factory()->create(['name' => 'Gamarra', 'department_id' => '20']);
        City::factory()->create(['name' => 'González', 'department_id' => '20']);
        City::factory()->create(['name' => 'La Gloria', 'department_id' => '20']);
        City::factory()->create(['name' => 'La Jagua de Ibirico', 'department_id' => '20']);
        City::factory()->create(['name' => 'Manaure', 'department_id' => '20']);
        City::factory()->create(['name' => 'Pailitas', 'department_id' => '20']);
        City::factory()->create(['name' => 'Pelaya', 'department_id' => '20']);
        City::factory()->create(['name' => 'Pueblo Bello', 'department_id' => '20']);
        City::factory()->create(['name' => 'Río de Oro', 'department_id' => '20']);
        City::factory()->create(['name' => 'La Paz', 'department_id' => '20']);
        City::factory()->create(['name' => 'San Alberto', 'department_id' => '20']);
        City::factory()->create(['name' => 'San Diego', 'department_id' => '20']);
        City::factory()->create(['name' => 'San Martín', 'department_id' => '20']);
        City::factory()->create(['name' => 'Tamalameque', 'department_id' => '20']);
        City::factory()->create(['name' => 'Montería', 'department_id' => '23']);
        City::factory()->create(['name' => 'Ayapel', 'department_id' => '23']);
        City::factory()->create(['name' => 'Buenavista', 'department_id' => '23']);
        City::factory()->create(['name' => 'Canalete', 'department_id' => '23']);
        City::factory()->create(['name' => 'Cereté', 'department_id' => '23']);
        City::factory()->create(['name' => 'Chimá', 'department_id' => '23']);
        City::factory()->create(['name' => 'Chinú', 'department_id' => '23']);
        City::factory()->create(['name' => 'Ciénaga de Oro', 'department_id' => '23']);
        City::factory()->create(['name' => 'Cotorra', 'department_id' => '23']);
        City::factory()->create(['name' => 'La Apartada', 'department_id' => '23']);
        City::factory()->create(['name' => 'Lorica', 'department_id' => '23']);
        City::factory()->create(['name' => 'Los Córdobas', 'department_id' => '23']);
        City::factory()->create(['name' => 'Momil', 'department_id' => '23']);
        City::factory()->create(['name' => 'Montelíbano', 'department_id' => '23']);
        City::factory()->create(['name' => 'Moñitos', 'department_id' => '23']);
        City::factory()->create(['name' => 'Planeta Rica', 'department_id' => '23']);
        City::factory()->create(['name' => 'Pueblo Nuevo', 'department_id' => '23']);
        City::factory()->create(['name' => 'Puerto Escondido', 'department_id' => '23']);
        City::factory()->create(['name' => 'Puerto Libertador', 'department_id' => '23']);
        City::factory()->create(['name' => 'Purísima', 'department_id' => '23']);
        City::factory()->create(['name' => 'Sahagún', 'department_id' => '23']);
        City::factory()->create(['name' => 'San Andrés Sotavento', 'department_id' => '23']);
        City::factory()->create(['name' => 'San Antero', 'department_id' => '23']);
        City::factory()->create(['name' => 'San Bernardo del Viento', 'department_id' => '23']);
        City::factory()->create(['name' => 'San Carlos', 'department_id' => '23']);
        City::factory()->create(['name' => 'San José de Uré', 'department_id' => '23']);
        City::factory()->create(['name' => 'San Pelayo', 'department_id' => '23']);
        City::factory()->create(['name' => 'Tierralta', 'department_id' => '23']);
        City::factory()->create(['name' => 'Tuchín', 'department_id' => '23']);
        City::factory()->create(['name' => 'Valencia', 'department_id' => '23']);
        City::factory()->create(['name' => 'Agua de Dios', 'department_id' => '25']);
        City::factory()->create(['name' => 'Albán', 'department_id' => '25']);
        City::factory()->create(['name' => 'Anapoima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Anolaima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Arbeláez', 'department_id' => '25']);
        City::factory()->create(['name' => 'Beltrán', 'department_id' => '25']);
        City::factory()->create(['name' => 'Bituima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Bojacá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cabrera', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cachipay', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cajicá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Caparrapí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Caqueza', 'department_id' => '25']);
        City::factory()->create(['name' => 'Carmen de Carupa', 'department_id' => '25']);
        City::factory()->create(['name' => 'Chaguaní', 'department_id' => '25']);
        City::factory()->create(['name' => 'Chía', 'department_id' => '25']);
        City::factory()->create(['name' => 'Chipaque', 'department_id' => '25']);
        City::factory()->create(['name' => 'Choachí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Chocontá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cogua', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cota', 'department_id' => '25']);
        City::factory()->create(['name' => 'Cucunubá', 'department_id' => '25']);
        City::factory()->create(['name' => 'El Colegio', 'department_id' => '25']);
        City::factory()->create(['name' => 'El Peñón', 'department_id' => '25']);
        City::factory()->create(['name' => 'El Rosal', 'department_id' => '25']);
        City::factory()->create(['name' => 'Facatativá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Fomeque', 'department_id' => '25']);
        City::factory()->create(['name' => 'Fosca', 'department_id' => '25']);
        City::factory()->create(['name' => 'Funza', 'department_id' => '25']);
        City::factory()->create(['name' => 'Fúquene', 'department_id' => '25']);
        City::factory()->create(['name' => 'Fusagasugá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Gachala', 'department_id' => '25']);
        City::factory()->create(['name' => 'Gachancipá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Gachetá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Gama', 'department_id' => '25']);
        City::factory()->create(['name' => 'Girardot', 'department_id' => '25']);
        City::factory()->create(['name' => 'Granada', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guachetá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guaduas', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guasca', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guataquí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guatavita', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guayabal de Siquima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Guayabetal', 'department_id' => '25']);
        City::factory()->create(['name' => 'Gutiérrez', 'department_id' => '25']);
        City::factory()->create(['name' => 'Jerusalén', 'department_id' => '25']);
        City::factory()->create(['name' => 'Junín', 'department_id' => '25']);
        City::factory()->create(['name' => 'La Calera', 'department_id' => '25']);
        City::factory()->create(['name' => 'La Mesa', 'department_id' => '25']);
        City::factory()->create(['name' => 'La Palma', 'department_id' => '25']);
        City::factory()->create(['name' => 'La Peña', 'department_id' => '25']);
        City::factory()->create(['name' => 'La Vega', 'department_id' => '25']);
        City::factory()->create(['name' => 'Lenguazaque', 'department_id' => '25']);
        City::factory()->create(['name' => 'Macheta', 'department_id' => '25']);
        City::factory()->create(['name' => 'Madrid', 'department_id' => '25']);
        City::factory()->create(['name' => 'Manta', 'department_id' => '25']);
        City::factory()->create(['name' => 'Medina', 'department_id' => '25']);
        City::factory()->create(['name' => 'Mosquera', 'department_id' => '25']);
        City::factory()->create(['name' => 'Nariño', 'department_id' => '25']);
        City::factory()->create(['name' => 'Nemocón', 'department_id' => '25']);
        City::factory()->create(['name' => 'Nilo', 'department_id' => '25']);
        City::factory()->create(['name' => 'Nimaima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Nocaima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Venecia', 'department_id' => '25']);
        City::factory()->create(['name' => 'Pacho', 'department_id' => '25']);
        City::factory()->create(['name' => 'Paime', 'department_id' => '25']);
        City::factory()->create(['name' => 'Pandi', 'department_id' => '25']);
        City::factory()->create(['name' => 'Paratebueno', 'department_id' => '25']);
        City::factory()->create(['name' => 'Pasca', 'department_id' => '25']);
        City::factory()->create(['name' => 'Puerto Salgar', 'department_id' => '25']);
        City::factory()->create(['name' => 'Pulí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Quebradanegra', 'department_id' => '25']);
        City::factory()->create(['name' => 'Quetame', 'department_id' => '25']);
        City::factory()->create(['name' => 'Quipile', 'department_id' => '25']);
        City::factory()->create(['name' => 'Apulo', 'department_id' => '25']);
        City::factory()->create(['name' => 'Ricaurte', 'department_id' => '25']);
        City::factory()->create(['name' => 'San Antonio del Tequendama', 'department_id' => '25']);
        City::factory()->create(['name' => 'San Bernardo', 'department_id' => '25']);
        City::factory()->create(['name' => 'San Cayetano', 'department_id' => '25']);
        City::factory()->create(['name' => 'San Francisco', 'department_id' => '25']);
        City::factory()->create(['name' => 'San Juan de Río Seco', 'department_id' => '25']);
        City::factory()->create(['name' => 'Sasaima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Sesquilé', 'department_id' => '25']);
        City::factory()->create(['name' => 'Sibaté', 'department_id' => '25']);
        City::factory()->create(['name' => 'Silvania', 'department_id' => '25']);
        City::factory()->create(['name' => 'Simijaca', 'department_id' => '25']);
        City::factory()->create(['name' => 'Soacha', 'department_id' => '25']);
        City::factory()->create(['name' => 'Sopó', 'department_id' => '25']);
        City::factory()->create(['name' => 'Subachoque', 'department_id' => '25']);
        City::factory()->create(['name' => 'Suesca', 'department_id' => '25']);
        City::factory()->create(['name' => 'Supatá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Susa', 'department_id' => '25']);
        City::factory()->create(['name' => 'Sutatausa', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tabio', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tausa', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tena', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tenjo', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tibacuy', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tibirita', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tocaima', 'department_id' => '25']);
        City::factory()->create(['name' => 'Tocancipá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Topaipí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Ubalá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Ubaque', 'department_id' => '25']);
        City::factory()->create(['name' => 'Villa De San Diego De Ubate', 'department_id' => '25']);
        City::factory()->create(['name' => 'Une', 'department_id' => '25']);
        City::factory()->create(['name' => 'Útica', 'department_id' => '25']);
        City::factory()->create(['name' => 'Vergara', 'department_id' => '25']);
        City::factory()->create(['name' => 'Vianí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Villagómez', 'department_id' => '25']);
        City::factory()->create(['name' => 'Villapinzón', 'department_id' => '25']);
        City::factory()->create(['name' => 'Villeta', 'department_id' => '25']);
        City::factory()->create(['name' => 'Viotá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Yacopí', 'department_id' => '25']);
        City::factory()->create(['name' => 'Zipacón', 'department_id' => '25']);
        City::factory()->create(['name' => 'Zipaquirá', 'department_id' => '25']);
        City::factory()->create(['name' => 'Quibdó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Acandí', 'department_id' => '27']);
        City::factory()->create(['name' => 'Alto Baudo', 'department_id' => '27']);
        City::factory()->create(['name' => 'Atrato', 'department_id' => '27']);
        City::factory()->create(['name' => 'Bagadó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Bahía Solano', 'department_id' => '27']);
        City::factory()->create(['name' => 'Bajo Baudó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Belén de Bajira', 'department_id' => '27']);
        City::factory()->create(['name' => 'Bojaya', 'department_id' => '27']);
        City::factory()->create(['name' => 'El Cantón del San Pablo', 'department_id' => '27']);
        City::factory()->create(['name' => 'Carmen del Darien', 'department_id' => '27']);
        City::factory()->create(['name' => 'Cértegui', 'department_id' => '27']);
        City::factory()->create(['name' => 'Condoto', 'department_id' => '27']);
        City::factory()->create(['name' => 'El Carmen de Atrato', 'department_id' => '27']);
        City::factory()->create(['name' => 'El Litoral del San Juan', 'department_id' => '27']);
        City::factory()->create(['name' => 'Istmina', 'department_id' => '27']);
        City::factory()->create(['name' => 'Juradó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Lloró', 'department_id' => '27']);
        City::factory()->create(['name' => 'Medio Atrato', 'department_id' => '27']);
        City::factory()->create(['name' => 'Medio Baudó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Medio San Juan', 'department_id' => '27']);
        City::factory()->create(['name' => 'Nóvita', 'department_id' => '27']);
        City::factory()->create(['name' => 'Nuquí', 'department_id' => '27']);
        City::factory()->create(['name' => 'Río Iro', 'department_id' => '27']);
        City::factory()->create(['name' => 'Río Quito', 'department_id' => '27']);
        City::factory()->create(['name' => 'Riosucio', 'department_id' => '27']);
        City::factory()->create(['name' => 'San José del Palmar', 'department_id' => '27']);
        City::factory()->create(['name' => 'Sipí', 'department_id' => '27']);
        City::factory()->create(['name' => 'Tadó', 'department_id' => '27']);
        City::factory()->create(['name' => 'Unguía', 'department_id' => '27']);
        City::factory()->create(['name' => 'Unión Panamericana', 'department_id' => '27']);
        City::factory()->create(['name' => 'Neiva', 'department_id' => '41']);
        City::factory()->create(['name' => 'Acevedo', 'department_id' => '41']);
        City::factory()->create(['name' => 'Agrado', 'department_id' => '41']);
        City::factory()->create(['name' => 'Aipe', 'department_id' => '41']);
        City::factory()->create(['name' => 'Algeciras', 'department_id' => '41']);
        City::factory()->create(['name' => 'Altamira', 'department_id' => '41']);
        City::factory()->create(['name' => 'Baraya', 'department_id' => '41']);
        City::factory()->create(['name' => 'Campoalegre', 'department_id' => '41']);
        City::factory()->create(['name' => 'Colombia', 'department_id' => '41']);
        City::factory()->create(['name' => 'Elías', 'department_id' => '41']);
        City::factory()->create(['name' => 'Garzón', 'department_id' => '41']);
        City::factory()->create(['name' => 'Gigante', 'department_id' => '41']);
        City::factory()->create(['name' => 'Guadalupe', 'department_id' => '41']);
        City::factory()->create(['name' => 'Hobo', 'department_id' => '41']);
        City::factory()->create(['name' => 'Iquira', 'department_id' => '41']);
        City::factory()->create(['name' => 'Isnos', 'department_id' => '41']);
        City::factory()->create(['name' => 'La Argentina', 'department_id' => '41']);
        City::factory()->create(['name' => 'La Plata', 'department_id' => '41']);
        City::factory()->create(['name' => 'Nátaga', 'department_id' => '41']);
        City::factory()->create(['name' => 'Oporapa', 'department_id' => '41']);
        City::factory()->create(['name' => 'Paicol', 'department_id' => '41']);
        City::factory()->create(['name' => 'Palermo', 'department_id' => '41']);
        City::factory()->create(['name' => 'Palestina', 'department_id' => '41']);
        City::factory()->create(['name' => 'Pital', 'department_id' => '41']);
        City::factory()->create(['name' => 'Pitalito', 'department_id' => '41']);
        City::factory()->create(['name' => 'Rivera', 'department_id' => '41']);
        City::factory()->create(['name' => 'Saladoblanco', 'department_id' => '41']);
        City::factory()->create(['name' => 'San Agustín', 'department_id' => '41']);
        City::factory()->create(['name' => 'Santa María', 'department_id' => '41']);
        City::factory()->create(['name' => 'Suaza', 'department_id' => '41']);
        City::factory()->create(['name' => 'Tarqui', 'department_id' => '41']);
        City::factory()->create(['name' => 'Tesalia', 'department_id' => '41']);
        City::factory()->create(['name' => 'Tello', 'department_id' => '41']);
        City::factory()->create(['name' => 'Teruel', 'department_id' => '41']);
        City::factory()->create(['name' => 'Timaná', 'department_id' => '41']);
        City::factory()->create(['name' => 'Villavieja', 'department_id' => '41']);
        City::factory()->create(['name' => 'Yaguará', 'department_id' => '41']);
        City::factory()->create(['name' => 'Riohacha', 'department_id' => '44']);
        City::factory()->create(['name' => 'Albania', 'department_id' => '44']);
        City::factory()->create(['name' => 'Barrancas', 'department_id' => '44']);
        City::factory()->create(['name' => 'Dibula', 'department_id' => '44']);
        City::factory()->create(['name' => 'Distracción', 'department_id' => '44']);
        City::factory()->create(['name' => 'El Molino', 'department_id' => '44']);
        City::factory()->create(['name' => 'Fonseca', 'department_id' => '44']);
        City::factory()->create(['name' => 'Hatonuevo', 'department_id' => '44']);
        City::factory()->create(['name' => 'La Jagua del Pilar', 'department_id' => '44']);
        City::factory()->create(['name' => 'Maicao', 'department_id' => '44']);
        City::factory()->create(['name' => 'Manaure', 'department_id' => '44']);
        City::factory()->create(['name' => 'San Juan del Cesar', 'department_id' => '44']);
        City::factory()->create(['name' => 'Uribia', 'department_id' => '44']);
        City::factory()->create(['name' => 'Urumita', 'department_id' => '44']);
        City::factory()->create(['name' => 'Villanueva', 'department_id' => '44']);
        City::factory()->create(['name' => 'Santa Marta', 'department_id' => '47']);
        City::factory()->create(['name' => 'Algarrobo', 'department_id' => '47']);
        City::factory()->create(['name' => 'Aracataca', 'department_id' => '47']);
        City::factory()->create(['name' => 'Ariguaní', 'department_id' => '47']);
        City::factory()->create(['name' => 'Cerro San Antonio', 'department_id' => '47']);
        City::factory()->create(['name' => 'Chivolo', 'department_id' => '47']);
        City::factory()->create(['name' => 'Ciénaga', 'department_id' => '47']);
        City::factory()->create(['name' => 'Concordia', 'department_id' => '47']);
        City::factory()->create(['name' => 'El Banco', 'department_id' => '47']);
        City::factory()->create(['name' => 'El Piñon', 'department_id' => '47']);
        City::factory()->create(['name' => 'El Retén', 'department_id' => '47']);
        City::factory()->create(['name' => 'Fundación', 'department_id' => '47']);
        City::factory()->create(['name' => 'Guamal', 'department_id' => '47']);
        City::factory()->create(['name' => 'Nueva Granada', 'department_id' => '47']);
        City::factory()->create(['name' => 'Pedraza', 'department_id' => '47']);
        City::factory()->create(['name' => 'Pijiño del Carmen', 'department_id' => '47']);
        City::factory()->create(['name' => 'Pivijay', 'department_id' => '47']);
        City::factory()->create(['name' => 'Plato', 'department_id' => '47']);
        City::factory()->create(['name' => 'Pueblo Viejo', 'department_id' => '47']);
        City::factory()->create(['name' => 'Remolino', 'department_id' => '47']);
        City::factory()->create(['name' => 'Sabanas de San Angel', 'department_id' => '47']);
        City::factory()->create(['name' => 'Salamina', 'department_id' => '47']);
        City::factory()->create(['name' => 'San Sebastián de Buenavista', 'department_id' => '47']);
        City::factory()->create(['name' => 'San Zenón', 'department_id' => '47']);
        City::factory()->create(['name' => 'Santa Ana', 'department_id' => '47']);
        City::factory()->create(['name' => 'Santa Bárbara de Pinto', 'department_id' => '47']);
        City::factory()->create(['name' => 'Sitionuevo', 'department_id' => '47']);
        City::factory()->create(['name' => 'Tenerife', 'department_id' => '47']);
        City::factory()->create(['name' => 'Zapayán', 'department_id' => '47']);
        City::factory()->create(['name' => 'Zona Bananera', 'department_id' => '47']);
        City::factory()->create(['name' => 'Villavicencio', 'department_id' => '50']);
        City::factory()->create(['name' => 'Acacias', 'department_id' => '50']);
        City::factory()->create(['name' => 'Barranca de Upía', 'department_id' => '50']);
        City::factory()->create(['name' => 'Cabuyaro', 'department_id' => '50']);
        City::factory()->create(['name' => 'Castilla la Nueva', 'department_id' => '50']);
        City::factory()->create(['name' => 'Cubarral', 'department_id' => '50']);
        City::factory()->create(['name' => 'Cumaral', 'department_id' => '50']);
        City::factory()->create(['name' => 'El Calvario', 'department_id' => '50']);
        City::factory()->create(['name' => 'El Castillo', 'department_id' => '50']);
        City::factory()->create(['name' => 'El Dorado', 'department_id' => '50']);
        City::factory()->create(['name' => 'Fuente de Oro', 'department_id' => '50']);
        City::factory()->create(['name' => 'Granada', 'department_id' => '50']);
        City::factory()->create(['name' => 'Guamal', 'department_id' => '50']);
        City::factory()->create(['name' => 'Mapiripán', 'department_id' => '50']);
        City::factory()->create(['name' => 'Mesetas', 'department_id' => '50']);
        City::factory()->create(['name' => 'La Macarena', 'department_id' => '50']);
        City::factory()->create(['name' => 'Uribe', 'department_id' => '50']);
        City::factory()->create(['name' => 'Lejanías', 'department_id' => '50']);
        City::factory()->create(['name' => 'Puerto Concordia', 'department_id' => '50']);
        City::factory()->create(['name' => 'Puerto Gaitán', 'department_id' => '50']);
        City::factory()->create(['name' => 'Puerto López', 'department_id' => '50']);
        City::factory()->create(['name' => 'Puerto Lleras', 'department_id' => '50']);
        City::factory()->create(['name' => 'Puerto Rico', 'department_id' => '50']);
        City::factory()->create(['name' => 'Restrepo', 'department_id' => '50']);
        City::factory()->create(['name' => 'San Carlos de Guaroa', 'department_id' => '50']);
        City::factory()->create(['name' => 'San Juan de Arama', 'department_id' => '50']);
        City::factory()->create(['name' => 'San Juanito', 'department_id' => '50']);
        City::factory()->create(['name' => 'San Martín', 'department_id' => '50']);
        City::factory()->create(['name' => 'Vista Hermosa', 'department_id' => '50']);
        City::factory()->create(['name' => 'Pasto', 'department_id' => '52']);
        City::factory()->create(['name' => 'Albán', 'department_id' => '52']);
        City::factory()->create(['name' => 'Aldana', 'department_id' => '52']);
        City::factory()->create(['name' => 'Ancuyá', 'department_id' => '52']);
        City::factory()->create(['name' => 'Arboleda', 'department_id' => '52']);
        City::factory()->create(['name' => 'Barbacoas', 'department_id' => '52']);
        City::factory()->create(['name' => 'Belén', 'department_id' => '52']);
        City::factory()->create(['name' => 'Buesaco', 'department_id' => '52']);
        City::factory()->create(['name' => 'Colón', 'department_id' => '52']);
        City::factory()->create(['name' => 'Consaca', 'department_id' => '52']);
        City::factory()->create(['name' => 'Contadero', 'department_id' => '52']);
        City::factory()->create(['name' => 'Córdoba', 'department_id' => '52']);
        City::factory()->create(['name' => 'Cuaspud', 'department_id' => '52']);
        City::factory()->create(['name' => 'Cumbal', 'department_id' => '52']);
        City::factory()->create(['name' => 'Cumbitara', 'department_id' => '52']);
        City::factory()->create(['name' => 'Chachagüí', 'department_id' => '52']);
        City::factory()->create(['name' => 'El Charco', 'department_id' => '52']);
        City::factory()->create(['name' => 'El Peñol', 'department_id' => '52']);
        City::factory()->create(['name' => 'El Rosario', 'department_id' => '52']);
        City::factory()->create(['name' => 'El Tablón de Gómez', 'department_id' => '52']);
        City::factory()->create(['name' => 'El Tambo', 'department_id' => '52']);
        City::factory()->create(['name' => 'Funes', 'department_id' => '52']);
        City::factory()->create(['name' => 'Guachucal', 'department_id' => '52']);
        City::factory()->create(['name' => 'Guaitarilla', 'department_id' => '52']);
        City::factory()->create(['name' => 'Gualmatán', 'department_id' => '52']);
        City::factory()->create(['name' => 'Iles', 'department_id' => '52']);
        City::factory()->create(['name' => 'Imués', 'department_id' => '52']);
        City::factory()->create(['name' => 'Ipiales', 'department_id' => '52']);
        City::factory()->create(['name' => 'La Cruz', 'department_id' => '52']);
        City::factory()->create(['name' => 'La Florida', 'department_id' => '52']);
        City::factory()->create(['name' => 'La Llanada', 'department_id' => '52']);
        City::factory()->create(['name' => 'La Tola', 'department_id' => '52']);
        City::factory()->create(['name' => 'La Unión', 'department_id' => '52']);
        City::factory()->create(['name' => 'Leiva', 'department_id' => '52']);
        City::factory()->create(['name' => 'Linares', 'department_id' => '52']);
        City::factory()->create(['name' => 'Los Andes', 'department_id' => '52']);
        City::factory()->create(['name' => 'Magüí', 'department_id' => '52']);
        City::factory()->create(['name' => 'Mallama', 'department_id' => '52']);
        City::factory()->create(['name' => 'Mosquera', 'department_id' => '52']);
        City::factory()->create(['name' => 'Nariño', 'department_id' => '52']);
        City::factory()->create(['name' => 'Olaya Herrera', 'department_id' => '52']);
        City::factory()->create(['name' => 'Ospina', 'department_id' => '52']);
        City::factory()->create(['name' => 'Francisco Pizarro', 'department_id' => '52']);
        City::factory()->create(['name' => 'Policarpa', 'department_id' => '52']);
        City::factory()->create(['name' => 'Potosí', 'department_id' => '52']);
        City::factory()->create(['name' => 'Providencia', 'department_id' => '52']);
        City::factory()->create(['name' => 'Puerres', 'department_id' => '52']);
        City::factory()->create(['name' => 'Pupiales', 'department_id' => '52']);
        City::factory()->create(['name' => 'Ricaurte', 'department_id' => '52']);
        City::factory()->create(['name' => 'Roberto Payán', 'department_id' => '52']);
        City::factory()->create(['name' => 'Samaniego', 'department_id' => '52']);
        City::factory()->create(['name' => 'Sandoná', 'department_id' => '52']);
        City::factory()->create(['name' => 'San Bernardo', 'department_id' => '52']);
        City::factory()->create(['name' => 'San Lorenzo', 'department_id' => '52']);
        City::factory()->create(['name' => 'San Pablo', 'department_id' => '52']);
        City::factory()->create(['name' => 'San Pedro de Cartago', 'department_id' => '52']);
        City::factory()->create(['name' => 'Santa Bárbara', 'department_id' => '52']);
        City::factory()->create(['name' => 'Santacruz', 'department_id' => '52']);
        City::factory()->create(['name' => 'Sapuyes', 'department_id' => '52']);
        City::factory()->create(['name' => 'Taminango', 'department_id' => '52']);
        City::factory()->create(['name' => 'Tangua', 'department_id' => '52']);
        City::factory()->create(['name' => 'San Andrés de Tumaco', 'department_id' => '52']);
        City::factory()->create(['name' => 'Túquerres', 'department_id' => '52']);
        City::factory()->create(['name' => 'Yacuanquer', 'department_id' => '52']);
        City::factory()->create(['name' => 'Cúcuta', 'department_id' => '54']);
        City::factory()->create(['name' => 'Abrego', 'department_id' => '54']);
        City::factory()->create(['name' => 'Arboledas', 'department_id' => '54']);
        City::factory()->create(['name' => 'Bochalema', 'department_id' => '54']);
        City::factory()->create(['name' => 'Bucarasica', 'department_id' => '54']);
        City::factory()->create(['name' => 'Cácota', 'department_id' => '54']);
        City::factory()->create(['name' => 'Cachirá', 'department_id' => '54']);
        City::factory()->create(['name' => 'Chinácota', 'department_id' => '54']);
        City::factory()->create(['name' => 'Chitagá', 'department_id' => '54']);
        City::factory()->create(['name' => 'Convención', 'department_id' => '54']);
        City::factory()->create(['name' => 'Cucutilla', 'department_id' => '54']);
        City::factory()->create(['name' => 'Durania', 'department_id' => '54']);
        City::factory()->create(['name' => 'El Carmen', 'department_id' => '54']);
        City::factory()->create(['name' => 'El Tarra', 'department_id' => '54']);
        City::factory()->create(['name' => 'El Zulia', 'department_id' => '54']);
        City::factory()->create(['name' => 'Gramalote', 'department_id' => '54']);
        City::factory()->create(['name' => 'Hacarí', 'department_id' => '54']);
        City::factory()->create(['name' => 'Herrán', 'department_id' => '54']);
        City::factory()->create(['name' => 'Labateca', 'department_id' => '54']);
        City::factory()->create(['name' => 'La Esperanza', 'department_id' => '54']);
        City::factory()->create(['name' => 'La Playa', 'department_id' => '54']);
        City::factory()->create(['name' => 'Los Patios', 'department_id' => '54']);
        City::factory()->create(['name' => 'Lourdes', 'department_id' => '54']);
        City::factory()->create(['name' => 'Mutiscua', 'department_id' => '54']);
        City::factory()->create(['name' => 'Ocaña', 'department_id' => '54']);
        City::factory()->create(['name' => 'Pamplona', 'department_id' => '54']);
        City::factory()->create(['name' => 'Pamplonita', 'department_id' => '54']);
        City::factory()->create(['name' => 'Puerto Santander', 'department_id' => '54']);
        City::factory()->create(['name' => 'Ragonvalia', 'department_id' => '54']);
        City::factory()->create(['name' => 'Salazar', 'department_id' => '54']);
        City::factory()->create(['name' => 'San Calixto', 'department_id' => '54']);
        City::factory()->create(['name' => 'San Cayetano', 'department_id' => '54']);
        City::factory()->create(['name' => 'Santiago', 'department_id' => '54']);
        City::factory()->create(['name' => 'Sardinata', 'department_id' => '54']);
        City::factory()->create(['name' => 'Silos', 'department_id' => '54']);
        City::factory()->create(['name' => 'Teorama', 'department_id' => '54']);
        City::factory()->create(['name' => 'Tibú', 'department_id' => '54']);
        City::factory()->create(['name' => 'Toledo', 'department_id' => '54']);
        City::factory()->create(['name' => 'Villa Caro', 'department_id' => '54']);
        City::factory()->create(['name' => 'Villa del Rosario', 'department_id' => '54']);
        City::factory()->create(['name' => 'Armenia', 'department_id' => '63']);
        City::factory()->create(['name' => 'Buenavista', 'department_id' => '63']);
        City::factory()->create(['name' => 'Calarcá', 'department_id' => '63']);
        City::factory()->create(['name' => 'Circasia', 'department_id' => '63']);
        City::factory()->create(['name' => 'Córdoba', 'department_id' => '63']);
        City::factory()->create(['name' => 'Filandia', 'department_id' => '63']);
        City::factory()->create(['name' => 'Génova', 'department_id' => '63']);
        City::factory()->create(['name' => 'La Tebaida', 'department_id' => '63']);
        City::factory()->create(['name' => 'Montenegro', 'department_id' => '63']);
        City::factory()->create(['name' => 'Pijao', 'department_id' => '63']);
        City::factory()->create(['name' => 'Quimbaya', 'department_id' => '63']);
        City::factory()->create(['name' => 'Salento', 'department_id' => '63']);
        City::factory()->create(['name' => 'Pereira', 'department_id' => '66']);
        City::factory()->create(['name' => 'Apía', 'department_id' => '66']);
        City::factory()->create(['name' => 'Balboa', 'department_id' => '66']);
        City::factory()->create(['name' => 'Belén de Umbría', 'department_id' => '66']);
        City::factory()->create(['name' => 'Dosquebradas', 'department_id' => '66']);
        City::factory()->create(['name' => 'Guática', 'department_id' => '66']);
        City::factory()->create(['name' => 'La Celia', 'department_id' => '66']);
        City::factory()->create(['name' => 'La Virginia', 'department_id' => '66']);
        City::factory()->create(['name' => 'Marsella', 'department_id' => '66']);
        City::factory()->create(['name' => 'Mistrató', 'department_id' => '66']);
        City::factory()->create(['name' => 'Pueblo Rico', 'department_id' => '66']);
        City::factory()->create(['name' => 'Quinchía', 'department_id' => '66']);
        City::factory()->create(['name' => 'Santa Rosa de Cabal', 'department_id' => '66']);
        City::factory()->create(['name' => 'Santuario', 'department_id' => '66']);
        City::factory()->create(['name' => 'Bucaramanga', 'department_id' => '68']);
        City::factory()->create(['name' => 'Aguada', 'department_id' => '68']);
        City::factory()->create(['name' => 'Albania', 'department_id' => '68']);
        City::factory()->create(['name' => 'Aratoca', 'department_id' => '68']);
        City::factory()->create(['name' => 'Barbosa', 'department_id' => '68']);
        City::factory()->create(['name' => 'Barichara', 'department_id' => '68']);
        City::factory()->create(['name' => 'Barrancabermeja', 'department_id' => '68']);
        City::factory()->create(['name' => 'Betulia', 'department_id' => '68']);
        City::factory()->create(['name' => 'Bolívar', 'department_id' => '68']);
        City::factory()->create(['name' => 'Cabrera', 'department_id' => '68']);
        City::factory()->create(['name' => 'California', 'department_id' => '68']);
        City::factory()->create(['name' => 'Capitanejo', 'department_id' => '68']);
        City::factory()->create(['name' => 'Carcasí', 'department_id' => '68']);
        City::factory()->create(['name' => 'Cepitá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Cerrito', 'department_id' => '68']);
        City::factory()->create(['name' => 'Charalá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Charta', 'department_id' => '68']);
        City::factory()->create(['name' => 'Chimá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Chipatá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Cimitarra', 'department_id' => '68']);
        City::factory()->create(['name' => 'Concepción', 'department_id' => '68']);
        City::factory()->create(['name' => 'Confines', 'department_id' => '68']);
        City::factory()->create(['name' => 'Contratación', 'department_id' => '68']);
        City::factory()->create(['name' => 'Coromoro', 'department_id' => '68']);
        City::factory()->create(['name' => 'Curití', 'department_id' => '68']);
        City::factory()->create(['name' => 'El Carmen de Chucurí', 'department_id' => '68']);
        City::factory()->create(['name' => 'El Guacamayo', 'department_id' => '68']);
        City::factory()->create(['name' => 'El Peñón', 'department_id' => '68']);
        City::factory()->create(['name' => 'El Playón', 'department_id' => '68']);
        City::factory()->create(['name' => 'Encino', 'department_id' => '68']);
        City::factory()->create(['name' => 'Enciso', 'department_id' => '68']);
        City::factory()->create(['name' => 'Florián', 'department_id' => '68']);
        City::factory()->create(['name' => 'Floridablanca', 'department_id' => '68']);
        City::factory()->create(['name' => 'Galán', 'department_id' => '68']);
        City::factory()->create(['name' => 'Gambita', 'department_id' => '68']);
        City::factory()->create(['name' => 'Girón', 'department_id' => '68']);
        City::factory()->create(['name' => 'Guaca', 'department_id' => '68']);
        City::factory()->create(['name' => 'Guadalupe', 'department_id' => '68']);
        City::factory()->create(['name' => 'Guapotá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Guavatá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Güepsa', 'department_id' => '68']);
        City::factory()->create(['name' => 'Hato', 'department_id' => '68']);
        City::factory()->create(['name' => 'Jesús María', 'department_id' => '68']);
        City::factory()->create(['name' => 'Jordán', 'department_id' => '68']);
        City::factory()->create(['name' => 'La Belleza', 'department_id' => '68']);
        City::factory()->create(['name' => 'Landázuri', 'department_id' => '68']);
        City::factory()->create(['name' => 'La Paz', 'department_id' => '68']);
        City::factory()->create(['name' => 'Lebríja', 'department_id' => '68']);
        City::factory()->create(['name' => 'Los Santos', 'department_id' => '68']);
        City::factory()->create(['name' => 'Macaravita', 'department_id' => '68']);
        City::factory()->create(['name' => 'Málaga', 'department_id' => '68']);
        City::factory()->create(['name' => 'Matanza', 'department_id' => '68']);
        City::factory()->create(['name' => 'Mogotes', 'department_id' => '68']);
        City::factory()->create(['name' => 'Molagavita', 'department_id' => '68']);
        City::factory()->create(['name' => 'Ocamonte', 'department_id' => '68']);
        City::factory()->create(['name' => 'Oiba', 'department_id' => '68']);
        City::factory()->create(['name' => 'Onzaga', 'department_id' => '68']);
        City::factory()->create(['name' => 'Palmar', 'department_id' => '68']);
        City::factory()->create(['name' => 'Palmas del Socorro', 'department_id' => '68']);
        City::factory()->create(['name' => 'Páramo', 'department_id' => '68']);
        City::factory()->create(['name' => 'Piedecuesta', 'department_id' => '68']);
        City::factory()->create(['name' => 'Pinchote', 'department_id' => '68']);
        City::factory()->create(['name' => 'Puente Nacional', 'department_id' => '68']);
        City::factory()->create(['name' => 'Puerto Parra', 'department_id' => '68']);
        City::factory()->create(['name' => 'Puerto Wilches', 'department_id' => '68']);
        City::factory()->create(['name' => 'Rionegro', 'department_id' => '68']);
        City::factory()->create(['name' => 'Sabana de Torres', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Andrés', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Benito', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Gil', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Joaquín', 'department_id' => '68']);
        City::factory()->create(['name' => 'San José de Miranda', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Miguel', 'department_id' => '68']);
        City::factory()->create(['name' => 'San Vicente de Chucurí', 'department_id' => '68']);
        City::factory()->create(['name' => 'Santa Bárbara', 'department_id' => '68']);
        City::factory()->create(['name' => 'Santa Helena del Opón', 'department_id' => '68']);
        City::factory()->create(['name' => 'Simacota', 'department_id' => '68']);
        City::factory()->create(['name' => 'Socorro', 'department_id' => '68']);
        City::factory()->create(['name' => 'Suaita', 'department_id' => '68']);
        City::factory()->create(['name' => 'Sucre', 'department_id' => '68']);
        City::factory()->create(['name' => 'Suratá', 'department_id' => '68']);
        City::factory()->create(['name' => 'Tona', 'department_id' => '68']);
        City::factory()->create(['name' => 'Valle de San José', 'department_id' => '68']);
        City::factory()->create(['name' => 'Vélez', 'department_id' => '68']);
        City::factory()->create(['name' => 'Vetas', 'department_id' => '68']);
        City::factory()->create(['name' => 'Villanueva', 'department_id' => '68']);
        City::factory()->create(['name' => 'Zapatoca', 'department_id' => '68']);
        City::factory()->create(['name' => 'Sincelejo', 'department_id' => '70']);
        City::factory()->create(['name' => 'Buenavista', 'department_id' => '70']);
        City::factory()->create(['name' => 'Caimito', 'department_id' => '70']);
        City::factory()->create(['name' => 'Coloso', 'department_id' => '70']);
        City::factory()->create(['name' => 'Corozal', 'department_id' => '70']);
        City::factory()->create(['name' => 'Coveñas', 'department_id' => '70']);
        City::factory()->create(['name' => 'Chalán', 'department_id' => '70']);
        City::factory()->create(['name' => 'El Roble', 'department_id' => '70']);
        City::factory()->create(['name' => 'Galeras', 'department_id' => '70']);
        City::factory()->create(['name' => 'Guaranda', 'department_id' => '70']);
        City::factory()->create(['name' => 'La Unión', 'department_id' => '70']);
        City::factory()->create(['name' => 'Los Palmitos', 'department_id' => '70']);
        City::factory()->create(['name' => 'Majagual', 'department_id' => '70']);
        City::factory()->create(['name' => 'Morroa', 'department_id' => '70']);
        City::factory()->create(['name' => 'Ovejas', 'department_id' => '70']);
        City::factory()->create(['name' => 'Palmito', 'department_id' => '70']);
        City::factory()->create(['name' => 'Sampués', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Benito Abad', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Juan de Betulia', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Marcos', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Onofre', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Pedro', 'department_id' => '70']);
        City::factory()->create(['name' => 'San Luis de Sincé', 'department_id' => '70']);
        City::factory()->create(['name' => 'Sucre', 'department_id' => '70']);
        City::factory()->create(['name' => 'Santiago de Tolú', 'department_id' => '70']);
        City::factory()->create(['name' => 'Tolú Viejo', 'department_id' => '70']);
        City::factory()->create(['name' => 'Ibagué', 'department_id' => '73']);
        City::factory()->create(['name' => 'Alpujarra', 'department_id' => '73']);
        City::factory()->create(['name' => 'Alvarado', 'department_id' => '73']);
        City::factory()->create(['name' => 'Ambalema', 'department_id' => '73']);
        City::factory()->create(['name' => 'Anzoátegui', 'department_id' => '73']);
        City::factory()->create(['name' => 'Armero', 'department_id' => '73']);
        City::factory()->create(['name' => 'Ataco', 'department_id' => '73']);
        City::factory()->create(['name' => 'Cajamarca', 'department_id' => '73']);
        City::factory()->create(['name' => 'Carmen de Apicala', 'department_id' => '73']);
        City::factory()->create(['name' => 'Casabianca', 'department_id' => '73']);
        City::factory()->create(['name' => 'Chaparral', 'department_id' => '73']);
        City::factory()->create(['name' => 'Coello', 'department_id' => '73']);
        City::factory()->create(['name' => 'Coyaima', 'department_id' => '73']);
        City::factory()->create(['name' => 'Cunday', 'department_id' => '73']);
        City::factory()->create(['name' => 'Dolores', 'department_id' => '73']);
        City::factory()->create(['name' => 'Espinal', 'department_id' => '73']);
        City::factory()->create(['name' => 'Falan', 'department_id' => '73']);
        City::factory()->create(['name' => 'Flandes', 'department_id' => '73']);
        City::factory()->create(['name' => 'Fresno', 'department_id' => '73']);
        City::factory()->create(['name' => 'Guamo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Herveo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Honda', 'department_id' => '73']);
        City::factory()->create(['name' => 'Icononzo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Lérida', 'department_id' => '73']);
        City::factory()->create(['name' => 'Líbano', 'department_id' => '73']);
        City::factory()->create(['name' => 'Mariquita', 'department_id' => '73']);
        City::factory()->create(['name' => 'Melgar', 'department_id' => '73']);
        City::factory()->create(['name' => 'Murillo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Natagaima', 'department_id' => '73']);
        City::factory()->create(['name' => 'Ortega', 'department_id' => '73']);
        City::factory()->create(['name' => 'Palocabildo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Piedras', 'department_id' => '73']);
        City::factory()->create(['name' => 'Planadas', 'department_id' => '73']);
        City::factory()->create(['name' => 'Prado', 'department_id' => '73']);
        City::factory()->create(['name' => 'Purificación', 'department_id' => '73']);
        City::factory()->create(['name' => 'Rio Blanco', 'department_id' => '73']);
        City::factory()->create(['name' => 'Roncesvalles', 'department_id' => '73']);
        City::factory()->create(['name' => 'Rovira', 'department_id' => '73']);
        City::factory()->create(['name' => 'Saldaña', 'department_id' => '73']);
        City::factory()->create(['name' => 'San Antonio', 'department_id' => '73']);
        City::factory()->create(['name' => 'San Luis', 'department_id' => '73']);
        City::factory()->create(['name' => 'Santa Isabel', 'department_id' => '73']);
        City::factory()->create(['name' => 'Suárez', 'department_id' => '73']);
        City::factory()->create(['name' => 'Valle de San Juan', 'department_id' => '73']);
        City::factory()->create(['name' => 'Venadillo', 'department_id' => '73']);
        City::factory()->create(['name' => 'Villahermosa', 'department_id' => '73']);
        City::factory()->create(['name' => 'Villarrica', 'department_id' => '73']);
        City::factory()->create(['name' => 'Cali', 'department_id' => '76']);
        City::factory()->create(['name' => 'Alcalá', 'department_id' => '76']);
        City::factory()->create(['name' => 'Andalucía', 'department_id' => '76']);
        City::factory()->create(['name' => 'Ansermanuevo', 'department_id' => '76']);
        City::factory()->create(['name' => 'Argelia', 'department_id' => '76']);
        City::factory()->create(['name' => 'Bolívar', 'department_id' => '76']);
        City::factory()->create(['name' => 'Buenaventura', 'department_id' => '76']);
        City::factory()->create(['name' => 'Buga', 'department_id' => '76']);
        City::factory()->create(['name' => 'Bugalagrande', 'department_id' => '76']);
        City::factory()->create(['name' => 'Caicedonia', 'department_id' => '76']);
        City::factory()->create(['name' => 'Calima', 'department_id' => '76']);
        City::factory()->create(['name' => 'Candelaria', 'department_id' => '76']);
        City::factory()->create(['name' => 'Cartago', 'department_id' => '76']);
        City::factory()->create(['name' => 'Dagua', 'department_id' => '76']);
        City::factory()->create(['name' => 'El Águila', 'department_id' => '76']);
        City::factory()->create(['name' => 'El Cairo', 'department_id' => '76']);
        City::factory()->create(['name' => 'El Cerrito', 'department_id' => '76']);
        City::factory()->create(['name' => 'El Dovio', 'department_id' => '76']);
        City::factory()->create(['name' => 'Florida', 'department_id' => '76']);
        City::factory()->create(['name' => 'Ginebra', 'department_id' => '76']);
        City::factory()->create(['name' => 'Guacarí', 'department_id' => '76']);
        City::factory()->create(['name' => 'Jamundí', 'department_id' => '76']);
        City::factory()->create(['name' => 'La Cumbre', 'department_id' => '76']);
        City::factory()->create(['name' => 'La Unión', 'department_id' => '76']);
        City::factory()->create(['name' => 'La Victoria', 'department_id' => '76']);
        City::factory()->create(['name' => 'Obando', 'department_id' => '76']);
        City::factory()->create(['name' => 'Palmira', 'department_id' => '76']);
        City::factory()->create(['name' => 'Pradera', 'department_id' => '76']);
        City::factory()->create(['name' => 'Restrepo', 'department_id' => '76']);
        City::factory()->create(['name' => 'Riofrío', 'department_id' => '76']);
        City::factory()->create(['name' => 'Roldanillo', 'department_id' => '76']);
        City::factory()->create(['name' => 'San Pedro', 'department_id' => '76']);
        City::factory()->create(['name' => 'Sevilla', 'department_id' => '76']);
        City::factory()->create(['name' => 'Toro', 'department_id' => '76']);
        City::factory()->create(['name' => 'Trujillo', 'department_id' => '76']);
        City::factory()->create(['name' => 'Tuluá', 'department_id' => '76']);
        City::factory()->create(['name' => 'Ulloa', 'department_id' => '76']);
        City::factory()->create(['name' => 'Versalles', 'department_id' => '76']);
        City::factory()->create(['name' => 'Vijes', 'department_id' => '76']);
        City::factory()->create(['name' => 'Yotoco', 'department_id' => '76']);
        City::factory()->create(['name' => 'Yumbo', 'department_id' => '76']);
        City::factory()->create(['name' => 'Zarzal', 'department_id' => '76']);
        City::factory()->create(['name' => 'Arauca', 'department_id' => '81']);
        City::factory()->create(['name' => 'Arauquita', 'department_id' => '81']);
        City::factory()->create(['name' => 'Cravo Norte', 'department_id' => '81']);
        City::factory()->create(['name' => 'Fortul', 'department_id' => '81']);
        City::factory()->create(['name' => 'Puerto Rondón', 'department_id' => '81']);
        City::factory()->create(['name' => 'Saravena', 'department_id' => '81']);
        City::factory()->create(['name' => 'Tame', 'department_id' => '81']);
        City::factory()->create(['name' => 'Yopal', 'department_id' => '85']);
        City::factory()->create(['name' => 'Aguazul', 'department_id' => '85']);
        City::factory()->create(['name' => 'Chámeza', 'department_id' => '85']);
        City::factory()->create(['name' => 'Hato Corozal', 'department_id' => '85']);
        City::factory()->create(['name' => 'La Salina', 'department_id' => '85']);
        City::factory()->create(['name' => 'Maní', 'department_id' => '85']);
        City::factory()->create(['name' => 'Monterrey', 'department_id' => '85']);
        City::factory()->create(['name' => 'Nunchía', 'department_id' => '85']);
        City::factory()->create(['name' => 'Orocué', 'department_id' => '85']);
        City::factory()->create(['name' => 'Paz de Ariporo', 'department_id' => '85']);
        City::factory()->create(['name' => 'Pore', 'department_id' => '85']);
        City::factory()->create(['name' => 'Recetor', 'department_id' => '85']);
        City::factory()->create(['name' => 'Sabanalarga', 'department_id' => '85']);
        City::factory()->create(['name' => 'Sácama', 'department_id' => '85']);
        City::factory()->create(['name' => 'San Luis de Gaceno', 'department_id' => '85']);
        City::factory()->create(['name' => 'Támara', 'department_id' => '85']);
        City::factory()->create(['name' => 'Tauramena', 'department_id' => '85']);
        City::factory()->create(['name' => 'Trinidad', 'department_id' => '85']);
        City::factory()->create(['name' => 'Villanueva', 'department_id' => '85']);
        City::factory()->create(['name' => 'Mocoa', 'department_id' => '86']);
        City::factory()->create(['name' => 'Colón', 'department_id' => '86']);
        City::factory()->create(['name' => 'Orito', 'department_id' => '86']);
        City::factory()->create(['name' => 'Puerto Asís', 'department_id' => '86']);
        City::factory()->create(['name' => 'Puerto Caicedo', 'department_id' => '86']);
        City::factory()->create(['name' => 'Puerto Guzmán', 'department_id' => '86']);
        City::factory()->create(['name' => 'Leguízamo', 'department_id' => '86']);
        City::factory()->create(['name' => 'Sibundoy', 'department_id' => '86']);
        City::factory()->create(['name' => 'San Francisco', 'department_id' => '86']);
        City::factory()->create(['name' => 'San Miguel', 'department_id' => '86']);
        City::factory()->create(['name' => 'Santiago', 'department_id' => '86']);
        City::factory()->create(['name' => 'Valle de Guamez', 'department_id' => '86']);
        City::factory()->create(['name' => 'Villagarzón', 'department_id' => '86']);
        City::factory()->create(['name' => 'San Andrés', 'department_id' => '88']);
        City::factory()->create(['name' => 'Providencia', 'department_id' => '88']);
        City::factory()->create(['name' => 'Leticia', 'department_id' => '91']);
        City::factory()->create(['name' => 'El Encanto', 'department_id' => '91']);
        City::factory()->create(['name' => 'La Chorrera', 'department_id' => '91']);
        City::factory()->create(['name' => 'La Pedrera', 'department_id' => '91']);
        City::factory()->create(['name' => 'La Victoria', 'department_id' => '91']);
        City::factory()->create(['name' => 'Miriti Paraná', 'department_id' => '91']);
        City::factory()->create(['name' => 'Puerto Alegría', 'department_id' => '91']);
        City::factory()->create(['name' => 'Puerto Arica', 'department_id' => '91']);
        City::factory()->create(['name' => 'Puerto Nariño', 'department_id' => '91']);
        City::factory()->create(['name' => 'Puerto Santander', 'department_id' => '91']);
        City::factory()->create(['name' => 'Tarapacá', 'department_id' => '91']);
        City::factory()->create(['name' => 'Inírida', 'department_id' => '94']);
        City::factory()->create(['name' => 'Barranco Minas', 'department_id' => '94']);
        City::factory()->create(['name' => 'Mapiripana', 'department_id' => '94']);
        City::factory()->create(['name' => 'San Felipe', 'department_id' => '94']);
        City::factory()->create(['name' => 'Puerto Colombia', 'department_id' => '94']);
        City::factory()->create(['name' => 'La Guadalupe', 'department_id' => '94']);
        City::factory()->create(['name' => 'Cacahual', 'department_id' => '94']);
        City::factory()->create(['name' => 'Pana Pana', 'department_id' => '94']);
        City::factory()->create(['name' => 'Morichal', 'department_id' => '94']);
        City::factory()->create(['name' => 'San José del Guaviare', 'department_id' => '95']);
        City::factory()->create(['name' => 'Calamar', 'department_id' => '95']);
        City::factory()->create(['name' => 'El Retorno', 'department_id' => '95']);
        City::factory()->create(['name' => 'Miraflores', 'department_id' => '95']);
        City::factory()->create(['name' => 'Mitú', 'department_id' => '97']);
        City::factory()->create(['name' => 'Caruru', 'department_id' => '97']);
        City::factory()->create(['name' => 'Pacoa', 'department_id' => '97']);
        City::factory()->create(['name' => 'Taraira', 'department_id' => '97']);
        City::factory()->create(['name' => 'Papunaua', 'department_id' => '97']);
        City::factory()->create(['name' => 'Yavaraté', 'department_id' => '97']);
        City::factory()->create(['name' => 'Puerto Carreño', 'department_id' => '99']);
        City::factory()->create(['name' => 'La Primavera', 'department_id' => '99']);
        City::factory()->create(['name' => 'Santa Rosalía', 'department_id' => '99']);
        City::factory()->create(['name' => 'Cumaribo', 'department_id' => '99']);

    }
}
